import jsPDF from "jspdf";
import {
  SUPERVISION_LEVELS,
  levelMeta,
  levelLabel,
  statusLabel,
  SupervisionLevel,
} from "@/lib/supervisionLevels";

export interface SupCompetency {
  id: string;
  parent_id: string | null;
  number: string;
  name: string;
  definition: string;
  domain: string;
}
export interface SupSeInput {
  competency_id: string;
  observations_count: number;
  evidence: string;
  self_assessment_level: SupervisionLevel;
  notes: string;
}
export interface SupSvInput {
  competency_id: string;
  final_level: SupervisionLevel;
  status: string;
  next_goal: string;
  notes: string;
}
export interface SupJournal {
  id: string;
  author_role: "supervisor" | "supervisee";
  entry_date: string;
  entry_type: string;
  related_competency_id: string | null;
  description: string;
  evidence: string;
  conclusion: string;
  supervisee_task: string;
  supervisor_task: string;
  next_check_date: string | null;
  notes: string;
}

interface HebrewFont {
  ALEF_REGULAR: string;
  ALEF_BOLD: string;
}

interface Args {
  superviseeName: string;
  generatedBy?: string;
  competencies: SupCompetency[];
  seInputs: Record<string, SupSeInput>;
  svInputs: Record<string, SupSvInput>;
  journal: SupJournal[];
  lang?: "en" | "he";
  /** Base64 Alef TTFs; required for Hebrew so glyphs render. Injected by the loader. */
  hebrewFont?: HebrewFont;
}

const L = {
  en: {
    title: "Supervision Report",
    supervisee: "Supervisee",
    generatedBy: "Generated by",
    date: "Date",
    summary: "Summary",
    overall: "Overall progress (supervisor rating)",
    totalComp: "Total competencies",
    independentPlus: "Independent or above",
    totalObs: "Total observations logged",
    byLevel: "By level",
    competencies: "Competencies",
    noComp: "No competencies recorded.",
    observations: "Observations",
    selfAssessment: "Self-assessment",
    supervisorRating: "Supervisor rating",
    status: "Status",
    nextGoal: "Next goal",
    supervisorNotes: "Supervisor notes",
    evidence: "Evidence",
    superviseeNotes: "Supervisee notes",
    journal: "Shared Journal",
    noJournal: "No journal entries.",
    by: "by",
    supervisor: "Supervisor",
    superviseeRole: "Supervisee",
    re: "re:",
    conclusion: "Conclusion",
    taskSe: "Task for supervisee",
    taskSv: "Task for supervisor",
    nextCheck: "Next check",
    page: "Page",
  },
  he: {
    title: 'דו"ח הדרכה',
    supervisee: "מודרך/ת",
    generatedBy: "הופק על ידי",
    date: "תאריך",
    summary: "סיכום",
    overall: "התקדמות כוללת (דירוג המדריך)",
    totalComp: "סך כשירויות",
    independentPlus: "עצמאי ומעלה",
    totalObs: "סך תצפיות שתועדו",
    byLevel: "לפי רמה",
    competencies: "כשירויות",
    noComp: "לא תועדו כשירויות.",
    observations: "תצפיות",
    selfAssessment: "הערכה עצמית",
    supervisorRating: "דירוג המדריך",
    status: "סטטוס",
    nextGoal: "יעד הבא",
    supervisorNotes: "הערות המדריך",
    evidence: "ראיות",
    superviseeNotes: "הערות המודרך/ת",
    journal: "יומן משותף",
    noJournal: "אין ערכי יומן.",
    by: "מאת",
    supervisor: "מדריך/ה",
    superviseeRole: "מודרך/ת",
    re: "בנוגע ל:",
    conclusion: "מסקנה",
    taskSe: "משימה למודרך/ת",
    taskSv: "משימה למדריך",
    nextCheck: "מעקב הבא",
    page: "עמוד",
  },
};

/**
 * Builds a full supervision report PDF for one supervisee: summary stats, the
 * competency tree (observations, self-assessment, supervisor rating, status,
 * goals & notes) and the shared journal.
 *
 * Supports English (LTR, Helvetica) and Hebrew (RTL, embedded Alef font). For
 * Hebrew, pass `hebrewFont`; `downloadSupervisionPdf` lazy-loads it automatically.
 * Returns the jsPDF doc so the caller can `.save(...)`.
 */
export function generateSupervisionPdf(args: Args): jsPDF {
  const { superviseeName, generatedBy, competencies, seInputs, svInputs, journal } = args;
  const lang: "en" | "he" = args.lang === "he" ? "he" : "en";
  const t = L[lang];
  const rtl = lang === "he";

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Register the Hebrew font (Alef) when needed; fall back to helvetica otherwise.
  let bodyFont = "helvetica";
  if (rtl && args.hebrewFont) {
    doc.addFileToVFS("Alef-Regular.ttf", args.hebrewFont.ALEF_REGULAR);
    doc.addFont("Alef-Regular.ttf", "alef", "normal");
    doc.addFileToVFS("Alef-Bold.ttf", args.hebrewFont.ALEF_BOLD);
    doc.addFont("Alef-Bold.ttf", "alef", "bold");
    bodyFont = "alef";
    doc.setR2L(true);
  }

  // Alef ships only normal + bold, so map italic -> normal in Hebrew mode.
  const setFont = (style: "normal" | "bold" | "italic") => {
    if (bodyFont === "alef") doc.setFont("alef", style === "bold" ? "bold" : "normal");
    else doc.setFont("helvetica", style);
  };

  const checkPage = (needed: number) => {
    if (y + needed > 272) {
      doc.addPage();
      y = 20;
    }
  };

  // Direction-aware paragraph writer. `indent` shifts away from the start edge.
  const write = (
    value: string,
    { size = 10, style = "normal", indent = 0 }: { size?: number; style?: "normal" | "bold" | "italic"; indent?: number } = {},
  ) => {
    setFont(style);
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(value, contentWidth - indent);
    for (const line of lines) {
      checkPage(6);
      if (rtl) doc.text(line, pageWidth - margin - indent, y, { align: "right" });
      else doc.text(line, margin + indent, y);
      y += size <= 9 ? 4.5 : 5;
    }
  };

  const heading = (label: string) => {
    checkPage(14);
    y += 2;
    setFont("bold");
    doc.setFontSize(13);
    doc.setTextColor(0);
    if (rtl) doc.text(label, pageWidth - margin, y, { align: "right" });
    else doc.text(label, margin, y);
    y += 3;
    doc.setDrawColor(210);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  };

  // ---- Title block ----
  setFont("bold");
  doc.setFontSize(18);
  if (rtl) doc.text(t.title, pageWidth - margin, y, { align: "right" });
  else doc.text(t.title, margin, y);
  y += 8;

  setFont("normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  const generatedOn = new Date().toLocaleDateString(lang === "he" ? "he-IL" : undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  const meta = [
    `${t.supervisee}: ${superviseeName || "—"}`,
    generatedBy ? `${t.generatedBy}: ${generatedBy}` : "",
    `${t.date}: ${generatedOn}`,
  ]
    .filter(Boolean)
    .join("   •   ");
  if (rtl) doc.text(meta, pageWidth - margin, y, { align: "right" });
  else doc.text(meta, margin, y);
  y += 4;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  doc.setTextColor(0);

  // ---- Summary ----
  const score = (c: SupCompetency) => levelMeta(svInputs[c.id]?.final_level || "not_started").score;
  const total = competencies.length;
  const overall = total
    ? Math.round((competencies.reduce((s, c) => s + score(c), 0) / (total * 4)) * 100)
    : 0;
  const independentPlus = competencies.filter((c) => score(c) >= 3).length;
  const totalObs = Object.values(seInputs).reduce((s, r) => s + (r.observations_count || 0), 0);

  heading(t.summary);
  write(`${t.overall}: ${overall}%`, { size: 10, style: "bold" });
  write(`${t.totalComp}: ${total}`);
  write(`${t.independentPlus}: ${independentPlus}`);
  write(`${t.totalObs}: ${totalObs}`);
  const dist = SUPERVISION_LEVELS.map((l) => `${levelLabel(l.value, lang)}: ${
    competencies.filter((c) => (svInputs[c.id]?.final_level || "not_started") === l.value).length
  }`).join("    ");
  write(`${t.byLevel} — ${dist}`, { size: 9, style: "italic" });

  // ---- Competencies (tree order) ----
  heading(t.competencies);
  if (!competencies.length) {
    write(t.noComp, { size: 10, style: "italic" });
  } else {
    const roots = competencies.filter((c) => !c.parent_id);
    const childrenOf = (id: string) => competencies.filter((c) => c.parent_id === id);

    const renderCompetency = (c: SupCompetency, depth: number) => {
      const indent = depth * 6;
      const se = seInputs[c.id];
      const sv = svInputs[c.id];

      checkPage(16);
      const titleParts = [c.number, c.name].filter(Boolean).join("  ");
      write(c.domain ? `${titleParts}   [${c.domain}]` : titleParts, { size: 10.5, style: "bold", indent });

      if (c.definition) {
        doc.setTextColor(110);
        write(c.definition, { size: 9, style: "italic", indent });
        doc.setTextColor(0);
      }

      const selfLbl = levelLabel((se?.self_assessment_level || "not_started") as SupervisionLevel, lang);
      const supLbl = levelLabel((sv?.final_level || "not_started") as SupervisionLevel, lang);
      const statusLbl = sv?.status ? statusLabel(sv.status, lang) : "—";
      doc.setTextColor(70);
      write(
        `${t.observations}: ${se?.observations_count ?? 0}   |   ${t.selfAssessment}: ${selfLbl}   |   ${t.supervisorRating}: ${supLbl}   |   ${t.status}: ${statusLbl}`,
        { size: 9, indent },
      );
      doc.setTextColor(0);

      if (sv?.next_goal) write(`${t.nextGoal}: ${sv.next_goal}`, { size: 9, indent });
      if (sv?.notes) write(`${t.supervisorNotes}: ${sv.notes}`, { size: 9, indent });
      if (se?.evidence) write(`${t.evidence}: ${se.evidence}`, { size: 9, indent });
      if (se?.notes) write(`${t.superviseeNotes}: ${se.notes}`, { size: 9, indent });
      y += 2;

      childrenOf(c.id).forEach((k) => renderCompetency(k, depth + 1));
    };

    roots.forEach((c) => renderCompetency(c, 0));
  }

  // ---- Journal ----
  heading(t.journal);
  if (!journal.length) {
    write(t.noJournal, { size: 10, style: "italic" });
  } else {
    const byId = new Map(competencies.map((c) => [c.id, c]));
    for (const j of journal) {
      checkPage(18);
      const related = j.related_competency_id ? byId.get(j.related_competency_id) : null;
      const who = j.author_role === "supervisor" ? t.supervisor : t.superviseeRole;
      const headLine = [
        j.entry_date,
        j.entry_type,
        `${t.by} ${who}`,
        related ? `${t.re} ${related.number} ${related.name}` : "",
      ]
        .filter(Boolean)
        .join("   •   ");
      write(headLine, { size: 10, style: "bold" });
      if (j.description) write(j.description, { size: 9 });
      if (j.evidence) write(`${t.evidence}: ${j.evidence}`, { size: 9 });
      if (j.conclusion) write(`${t.conclusion}: ${j.conclusion}`, { size: 9 });
      if (j.supervisee_task) write(`${t.taskSe}: ${j.supervisee_task}`, { size: 9 });
      if (j.supervisor_task) write(`${t.taskSv}: ${j.supervisor_task}`, { size: 9 });
      if (j.next_check_date) write(`${t.nextCheck}: ${j.next_check_date}`, { size: 9 });
      y += 3;
      doc.setDrawColor(230);
      doc.line(margin, y, pageWidth - margin, y);
      y += 4;
    }
  }

  // ---- Footer ----
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    setFont("normal");
    doc.setFontSize(8);
    doc.setTextColor(160);
    const footer = `Blueprint CBS — ${t.title} — ${superviseeName || ""} — ${t.page} ${i}/${totalPages}`;
    if (rtl) doc.text(footer, pageWidth - margin, 290, { align: "right" });
    else doc.text(footer, margin, 290);
  }

  return doc;
}

/** Build and download with a sensible filename. Lazy-loads the Hebrew font when needed. */
export async function downloadSupervisionPdf(args: Args): Promise<void> {
  let hebrewFont = args.hebrewFont;
  if (args.lang === "he" && !hebrewFont) {
    hebrewFont = await import("./fonts/alefHebrew");
  }
  const doc = generateSupervisionPdf({ ...args, hebrewFont });
  const safeName = (args.superviseeName || "supervisee")
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-|-$/g, "");
  const stamp = new Date().toISOString().slice(0, 10);
  doc.save(`Supervision-${safeName || "supervisee"}-${stamp}.pdf`);
}
