// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/who-am-i.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var who_am_i_default = defineTool({
  name: "who_am_i",
  title: "Who am I",
  description: "Return the signed-in Blueprint user's profile (name, email, roles).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("id, full_name, email, avatar_url").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? profile?.email ?? null,
      full_name: profile?.full_name ?? null,
      avatar_url: profile?.avatar_url ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_upcoming_sessions_default = defineTool2({
  name: "list_upcoming_sessions",
  title: "List upcoming sessions",
  description: "List the signed-in user's upcoming Blueprint sessions (as client, therapist, or supervisee). Ordered by session_date ascending. RLS applies.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of sessions to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabase.from("sessions").select("id, title, session_date, status, meeting_link, meeting_platform").gte("session_date", now).order("session_date", { ascending: true }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-tasks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_my_tasks_default = defineTool3({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List the signed-in user's open tasks from the productivity task board.",
  inputSchema: {
    include_completed: z2.boolean().optional().describe("Include completed tasks (default false)."),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_completed, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("user_tasks").select("id, title, description, priority, status, due_date, is_completed, created_at").eq("user_id", ctx.getUserId()).order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (!include_completed) q = q.eq("is_completed", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_notifications_default = defineTool4({
  name: "list_notifications",
  title: "List notifications",
  description: "List the signed-in user's most recent Blueprint notifications.",
  inputSchema: {
    unread_only: z3.boolean().optional().describe("Return only unread notifications (default false)."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("notifications").select("id, title, message, type, is_read, link, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 15);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wcqjmjceelcainyyqjmi";
var mcp_default = defineMcp({
  name: "blueprint-mcp",
  title: "Blueprint",
  version: "0.1.0",
  instructions: "Blueprint (Applied Constructional Behavioural Services) tools. Read the signed-in user's profile, upcoming sessions, tasks, and notifications. All access respects the app's role-based permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [who_am_i_default, list_upcoming_sessions_default, list_my_tasks_default, list_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
